//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VTrans.rc
//
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_PROGRESS_PANE      102
#define ID_INDICATOR_CLAUSE_PROGRESS_PANE 103
#define ID_INDICATOR_SENTENCE_PROGRESS_PANE 104
#define ID_INDICATOR_TEXT_PROGRESS_PANE 105
#define IDC_INDICATOR_CLAUSE_PROGRESS_PANE 106
#define ID_INDICATOR_REMAINING_TIME     107
#define ID_INDICATOR_GRAPHIC_CLAUSE_PROGRESS_PANE 108
#define ID_INDICATOR_NUMERIC_CLAUSE_PROGRESS_PANE 109
#define ID_INDICATOR_GRAPHIC_SENTENCE_PROGRESS_PANE 110
#define ID_INDICATOR_NUMERIC_SENTENCE_PROGRESS_PANE 111
#define ID_INDICATOR_GRAPHIC_TEXT_PROGRESS_PANE 112
#define ID_INDICATOR_NUMERIC_TEXT_PROGRESS_PANE 113
#define IDR_MAINFRAME                   128
#define IDR_VTRANSTYPE                  129
#define IDI_ICON1                       130
#define IDD_OPTIONS_DIALOG              133
#define IDD_STATUS_DIALOG               138
#define IDB_BITMAP1                     139
#define IDB_BITMAP2                     140
#define IDB_BITMAP3                     141
#define IDB_BITMAP4                     142
#define IDB_BITMAP5                     143
#define IDD_FILE_OPEN_DIALOG            144
#define IDC_ENGLISH_WORDKIND_COMBO      1000
#define IDC_HOMEPAGE_EDIT               1001
#define IDC_WORD_EDIT                   1002
#define IDC_REGISTRY_KEY_EDIT           1003
#define IDC_VOCABLE_FORWARD             1004
#define IDC_CHECK1                      1004
#define IDC_EMAIL_EDIT                  1005
#define IDC_ENGLISH_SCROLLVERT          1006
#define IDC_CONFIGURATION_STATIC        1006
#define IDC_GERMAN_SCROLLVERT           1007
#define IDC_ENSURE_USER_WANTS_MODIFICATION_CHECK 1007
#define IDC_ENSURE_USER_WANTS_DELETION_CHECK 1008
#define IDC_MAX_CHARS_PER_LINE_EDIT     1009
#define IDC_AMOUNT_STATIC               1010
#define IDC_PARSING_PROGRESS            1011
#define IDC_SENTENCE_PROGRESS           1012
#define IDC_TEXT_PROGRESS               1013
#define IDC_CASE_SENSITIVE_CHECK        1014
#define IDC_TEXT_PROGRESS_CHECK         1015
#define IDC_SENTENCE_PROGRESS_CHECK     1016
#define IDC_CLAUSE_PROGRESS_CHECK       1017
#define IDC_CLAUSE_PROGRESS_MODE_GRAHIC_CHECK 1022
#define IDC_CLAUSE_PROGRESS_MODE_GRAPHIC_CHECK 1022
#define IDC_CLAUSE_PROGRESS_MODE_NUMERIC_CHECK 1023
#define IDC_PROGNOSTICED_REMAINING_TIME_CHECK 1024
#define IDC_SENTENCE_PROGRESS_MODE_GRAHIC_CHECK 1025
#define IDC_SENTENCE_PROGRESS_MODE_GRAPHIC_CHECK 1025
#define IDC_SENTENCE_PROGRESS_MODE_NUMERIC_CHECK 1026
#define IDC_TEXT_PROGRESS_MODE_GRAHIC_CHECK 1027
#define IDC_TEXT_PROGRESS_MODE_GRAPHIC_CHECK 1027
#define IDC_TEXT_PROGRESS_MODE_NUMERIC_CHECK 1028
#define IDC_BUFFER_OUTPUT_CHECK         1029
#define IDC_ROUGH_GRAPHIC_CLAUSE_PROGRESS_RADIO 1030
#define IDC_SMOOTH_GRAPHIC_CLAUSE_PROGRESS_RADIO 1031
#define IDC_ROUGH_GRAPHIC_SENTENCE_PROGRESS_RADIO 1032
#define IDC_SMOOTH_GRAPHIC_SENTENCE_PROGRESS_RADIO 1033
#define IDC_ROUGH_GRAPHIC_TEXT_PROGRESS_RADIO 1034
#define IDC_SMOOTH_GRAPHIC_TEXT_PROGRESS_RADIO 1035
#define IDC_THREAD_PRIORITY_SLIDER      1037
#define IDC_ALLOW_LOW_LETTER_AT_THE_BEGINNING_OF_SENTENCE_CHECK 1038
#define IDC_ADOPT_GRAMMATICALLY_INCORRECT_SENTENCES_CHECK 1039
#define IDC_AUTOMATIC_FORMATTING_CHECK  1040
#define IDC_CHECK2                      1041
#define IDC_CHECK3                      1042
#define IDC_LOAD_PROGRESS               1044
#define IDC_BYTES_INSERTED_STATIC       1045
#define IDC_BYTES_TOTAL_STATIC          1046
#define IDC_ACTION_STATIC               1047
#define IDC_TEXT_STATIC                 1048
#define ID_BUTTON32771                  32771
#define ID_VIEW_VOCABLEEDITOR           32772
#define ID_BUTTON32773                  32773
#define ID_TRANSLATE_BUTTON             32774
#define ID_EXTRAS_COUNT_WORDS           32775
#define ID_VOCABLE_EDITOR_BUTTON        32776
#define ID_VIEW_SEARCH_FORM             32777
#define ID_BUTTON32778                  32778
#define ID_BUTTON32779                  32779
#define ID_BUTTON32780                  32780
#define ID_ADD_VOCABLE_BUTTON           32781
#define ID_OVERWRITE_VOCABLE_BUTTON     32784
#define ID_DELETE_VOCABLE_BUTTON        32785
#define ID_COMBOBOX_BUTTON              32786
#define ID_EXTRAS_OPTIONEN              32787
#define ID_NEXT_VOCABLE_BUTTON          32788
#define ID_PREVIOUS_VOCABLE_BUTTON      32789
#define ID_TRANSLATE_AUTOMATICALLY_IF_TEXTMODIFICATION_BUTTON 32790
#define ID_EDIT_MARKALL                 32791
#define ID_BEARBEITEN_LSCHEN            32792
#define ID_EDIT_MARK_ALL                32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
