/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vtrans_dynlib_VTransDynLibJNI */

#ifndef _Included_vtrans_dynlib_VTransDynLibJNI
#define _Included_vtrans_dynlib_VTransDynLibJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vtrans_dynlib_VTransDynLibJNI
 * Method:    Init
 * Signature: (Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL Java_vtrans_1dynlib_VTransDynLibJNI_Init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vtrans_dynlib_VTransDynLibJNI
 * Method:    Translate
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_vtrans_1dynlib_VTransDynLibJNI_Translate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vtrans_dynlib_VTransDynLibJNI
 * Method:    FreeMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vtrans_1dynlib_VTransDynLibJNI_FreeMemory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
